version: '3'

services:
  nodejs:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
     - "3000:3000"
    networks: 
     - app-network
    volumes: 
     - ./backend/:/home/node/app
     - node_modules:/home/node/app/node_modules
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon server.js    

  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    volumes:
     - dbdata:/data/db
    networks:
     - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
     - web-root:/var/www/html
     - ./nginx-conf:/etc/nginx/conf.d
     - certbot-etc:/etc/letsencrypt
     - certbot-var:/var/lib/letsencrpyt
     - dhparam:/etc/ssl/certs
    ports:
     - "80:80"
     - "443:443"
    depends_on:
     - nodejs 
    networks:
     - app-network

  coturn: 
    image: 'instrumentisto/coturn'
    container_name: coturn
    restart: unless-stopped
    networks:
     - app-network  
    ports:
     - "3478:3478/udp" 
    volumes:
     - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf
     
  kraken_listen_only: 
    build:
      context: ./kraken_listen_only/
      dockerfile: Dockerfile
    image: kraken_listen_only
    container_name: kraken_listen_only
#    volumes: 
#     - "./kraken_listen_only/config:./config"
    ports:
     - "7000:7000"
    restart: unless-stopped
    networks:
     - app-network  
#    depends_on:
#     - coturn

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
     - certbot-etc:/etc/letsencrypt
     - certbot-var:/var/lib/letsencrypt
     - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email seth.kimmel3@gmail.com --agree-tos --no-eff-email --force-renewal -d roundtable.audio -d www.roundtable.audio -d hackernews.roundtable.audio -d www.hackernews.roundtable.audio

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ./client-code/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/seth/discourse.fm/dhparam/
      o: bind
  dbdata:
  node_modules:

networks:
  app-network:
    driver: bridge
